### ISSUE TITLE
Allow use of @everyone mention in messages

### ISSUE THREAD

**Issue by Gyoo** [Gyoo/Discord-Streambot#13]
It was suggested to add the @everyone mention to the messages of Streambot with a command like `!streambot toggle_everyone`

**Comment by EEwing** [comment]
Can you provide an explanation of how to implement the feature added in this issue? A simple explanation before closing the issues will help people who want to know what to do about an issue that's been closed. Thanks!

**Comment by Gyoo** [comment]
My bad. For this one it's `!streambot toggle everyone` but it's likely to change when I add #15
