### ISSUE TITLE
Feature request: Personal stream notifications

### ISSUE THREAD

**Issue by execut4ble** [Gyoo/Discord-Streambot#15]
I thought it would be a good idea to have the bot notify you whenever someone goes live.

Right now there's an option to do @everyone but it might get annoying for some people in your Discord server. How about a command like !streambot notifyme or !streambot subscribe and the bot would memorize and include a @username mention in their next stream notification, together with everyone else who chose to be notified? 

This way you'd get notifications whenever there's a stream and it wouldn't notify everyone.

**Comment by Gyoo** [comment]
Thanks for the feedback, that's actually quite clever !

This shouldn't be too hard to implement, I'll see if I do it as a small update or part of the next big update I'm planning (mostly based on #11 that should make a lot of changes in the code once again)

**Comment by Gyoo** [comment]
Just implemented that. Commands are now `!streambot notify me` for everyone to add their name to the mentions list, and `!streambot notify everyone` for the managers to add the @everyone mention to the announces.
