### ISSUE TITLE
Help message for move is wrong

### ISSUE THREAD

**Issue by Quitch** [Gyoo/Discord-Streambot#36]
"Moves the bot announces to another channel (Must use the #channel identifier !)"

So, a couple of errors here:
1. "bot announces" should be "bot's announcements"
2. "#channel identifier" should be "channel identifier" (since the #channel identifier would mean the number without the hash), or "channel identifier (including the leading #)"

**Comment by Gyoo** [comment]
Fixed in next update.

Message is now the following : `move <channel>` : Moves the bot announcements to another channel (Must use the channel identifier ! Example : `#public` )
