### ISSUE TITLE
Bot should write message to channel on move

### ISSUE THREAD

**Issue by Quitch** [Gyoo/Discord-Streambot#39]
To show that the bot has been correctly assigned to the channel and has the right permissions it should send a test message to that channel once it's moved there "Streambot will now announce streams in this channel." or some such.

**Comment by Gyoo** [comment]
Already done.

**Comment by Quitch** [comment]
Minor point: it writes to the channel the command was issued in, not the channel it's going to announce in. The latter would allow it to show it has the relevant permissions.
