### ISSUE TITLE
[Suggestion] Leave out your properties file for safety purposes....

### ISSUE THREAD

**Issue by BaiqingL** [Gyoo/Discord-Streambot#46]
It seems like you have left in your token and passwords, that may be a mistake however I would recommend that you delete them to prevent any further harm. I may have tested to see if it is a dummy, I apologize in advanced for that.

**Comment by BaiqingL** [comment]
Token tested:
OTk4NTI5MDQ1MDQwMDQ2MDg.Cirfxw.UHJMPx_jXyW6upFZRpDramBWUjI
Logged in as Streambot.

**Comment by ghost** [comment]
Yeah... @Gyoo You'll want to scrub that file from version control and refresh your token asap. This is a big deal if your bot can be invited to other servers, cus then if your bot gets compromised, that impacts a bunch of people.

**Comment by Gyoo** [comment]
I just deleted the bot account so 🤷‍♂️

**Comment by BaiqingL** [comment]
lol good to know
